# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define percy orb
orbs:
  percy: percy/agent@0.1.3

# Define tests jobs
jobs:
  install_and_build:
    docker:
      - image: cimg/ruby:2.7.2-browsers

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            npm install
            gem install percy-cli

      - run:
          name: build
          command: |
            npm run build
            percy snapshot build

# Define test workflow
workflows:
  test:
    jobs:
      - install_and_build
      - percy/finalize_all:
          requires:
            - install_and_build
